name: Test

on:
  push:
    branches:
      - develop

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test
